### ISSUE TITLE
librarian-chef install fails

### ISSUE THREAD

**Issue by mpuels** [jckuester/lamp-for-aws#1]
The command `librarian-chef install` fails with the error message

    remote: Repository not found.
    fatal: repository 'https://github.com/jckuester/lamp-for-aws-cookbook.git/' not found

Where can I find the referenced git repository?

**Comment by jckuester** [comment]
I moved this repo to our cloud org https://github.com/cloudetc/lamp-stack-for-aws. Please clone it there! Sorry, I haven't deleted it yet here.
